Repository AcrossTec/SysCredit, pull requests merged in 2024-01, with the labels that each got.

#230 feat: Added Login, Recover and Create Account Views
  SysCredit/App.xaml
  SysCredit/AppShell.xaml
  SysCredit/Resources/Images/Login/header_recuperacion.svg
  SysCredit/Resources/Images/Login/login_parte_superior.svg
  SysCredit/Resources/Styles/Colors.xaml
  SysCredit/Resources/Styles/LoginStyles.xaml
  SysCredit/Resources/Styles/LoginStyles.xaml.cs
  SysCredit/SysCredit.csproj
  SysCredit/Views/Users/LoginPage.xaml
  SysCredit/Views/Users/RecoverAccountPage.xaml
  SysCredit/Views/Users/UserRegistrationPage.xaml
Labels: frontend, .Net MAUI

#232 fix: Change the Status Bar Color In The Splash Screen
  SysCredit/Views/SplashScreenPage.xaml
Labels: .Net MAUI

#234 refactor: Modify the presentation views and rename presentation images
  SysCredit/Resources/Images/Presentation/accessibility.svg
  SysCredit/Resources/Images/Presentation/clock.svg
  SysCredit/Resources/Images/Presentation/lighthouse.svg
  SysCredit/Resources/Images/Presentation/order.svg
  SysCredit/SysCredit.csproj
  SysCredit/Views/Presentations/PresentationPage1.xaml
  SysCredit/Views/Presentations/PresentationPage2.xaml
  SysCredit/Views/Presentations/PresentationPage3.xaml
  SysCredit/Views/Presentations/PresentationPage4.xaml
Labels: .Net MAUI

#233 feat[maui]: Added Footer and Improved Horizontal Design
  SysCredit/Resources/Styles/LoginStyles.xaml
  SysCredit/Views/Users/LoginPage.xaml
  SysCredit/Views/Users/RecoverAccountPage.xaml
Labels: frontend, .Net MAUI

#235 refactor[maui]: Rename the footer view control
  SysCredit/Controls/PresentationFooterView.xaml.cs
  SysCredit/Controls/SysCreditFooterView.xaml
  SysCredit/Controls/SysCreditFooterView.xaml.cs
  SysCredit/Views/Presentations/PresentationPage1.xaml
  SysCredit/Views/Presentations/PresentationPage2.xaml
  SysCredit/Views/Presentations/PresentationPage3.xaml
  SysCredit/Views/Presentations/PresentationPage4.xaml
  SysCredit/Views/Users/LoginPage.xaml
  SysCredit/Views/Users/RecoverAccountPage.xaml
Labels: .Net MAUI

#239 feat[maui]: Responsive Design for Login and Recover Account Page
  SysCredit/Resources/Styles/LoginStyles.xaml
  SysCredit/Views/Users/LoginPage.xaml
  SysCredit/Views/Users/RecoverAccountPage.xaml
Labels: frontend, .Net MAUI

#238 feat[maui]: Add Catalogs Pages
  SysCredit/App.xaml
  SysCredit/AppShell.xaml
  SysCredit/MauiProgram.cs
  SysCredit/Models/Catalogs/LoanType.cs
  SysCredit/Properties/SysCreditResources.Designer.cs
  SysCredit/Properties/SysCreditResources.es.resx
  SysCredit/Properties/SysCreditResources.resx
  SysCredit/Resources/Images/catalog_icon.svg
  SysCredit/Resources/Images/loan_types_icon.svg
  SysCredit/Resources/Images/payment_frequency_icon.svg
  SysCredit/Resources/Images/relationship_icon.svg
  SysCredit/Resources/Styles/ButtonIconStyle.xaml
  SysCredit/Resources/Styles/ButtonIconStyle.xaml.cs
  SysCredit/Resources/Styles/Colors.xaml
  SysCredit/SysCredit.sln
  SysCredit/ViewModels/Catalogs/CatalogsPageViewModel.cs
  SysCredit/ViewModels/Catalogs/LoanTypes/LoanTypesCrudPageViewModel.cs
  SysCredit/ViewModels/Catalogs/LoanTypes/UpdateLoanTypePageViewModel.cs
  SysCredit/ViewModels/Catalogs/LoanTypes/ViewLoanTypeCatalogPageViewModel.cs
  SysCredit/ViewModels/Catalogs/PaymentFrequencies/PaymentFrequenciesCrudPageViewModel.cs
  SysCredit/ViewModels/Catalogs/Relationships/RelationshipsCrudPageViewModel.cs
  SysCredit/ViewModels/MainViewModel.cs
  SysCredit/Views/Catalogs/CatalogsPage.xaml
  SysCredit/Views/Catalogs/CatalogsPage.xaml.cs
  SysCredit/Views/Catalogs/LoanTypes/DeleteLoanTypePage.xaml
  SysCredit/Views/Catalogs/LoanTypes/DeleteLoanTypePage.xaml.cs
  SysCredit/Views/Catalogs/LoanTypes/LoanTypesCrudPage.xaml
  SysCredit/Views/Catalogs/LoanTypes/LoanTypesCrudPage.xaml.cs
  SysCredit/Views/Catalogs/LoanTypes/UpdateLoanTypePage.xaml
  SysCredit/Views/Catalogs/LoanTypes/UpdateLoanTypePage.xaml.cs
  SysCredit/Views/Catalogs/LoanTypes/ViewLoanTypeCatalogPage.xaml
  SysCredit/Views/Catalogs/LoanTypes/ViewLoanTypeCatalogPage.xaml.cs
  SysCredit/Views/Catalogs/PaymentFrequencies/DeletePaymentFrequencyPage.xaml
  SysCredit/Views/Catalogs/PaymentFrequencies/DeletePaymentFrequencyPage.xaml.cs
  SysCredit/Views/Catalogs/PaymentFrequencies/PaymentFrequenciesCrudPage.xaml
  SysCredit/Views/Catalogs/PaymentFrequencies/PaymentFrequenciesCrudPage.xaml.cs
  SysCredit/Views/Catalogs/PaymentFrequencies/UpdatePaymentFrequencyPage.xaml
  SysCredit/Views/Catalogs/PaymentFrequencies/UpdatePaymentFrequencyPage.xaml.cs
  SysCredit/Views/Catalogs/PaymentFrequencies/ViewPaymentFrequencyCatalogPage.xaml
  SysCredit/Views/Catalogs/PaymentFrequencies/ViewPaymentFrequencyCatalogPage.xaml.cs
  SysCredit/Views/Catalogs/Relationships/DeleteRelationshipPage.xaml
  SysCredit/Views/Catalogs/Relationships/DeleteRelationshipPage.xaml.cs
  SysCredit/Views/Catalogs/Relationships/RelationshipsCrudPage.xaml
  SysCredit/Views/Catalogs/Relationships/RelationshipsCrudPage.xaml.cs
  SysCredit/Views/Catalogs/Relationships/UpdateRelationshipPage.xaml
  SysCredit/Views/Catalogs/Relationships/UpdateRelationshipPage.xaml.cs
  SysCredit/Views/Catalogs/Relationships/ViewRelationshipCatalogPage.xaml
  SysCredit/Views/Catalogs/Relationships/ViewRelationshipCatalogPage.xaml.cs
  SysCredit/Views/MainPage.xaml
Labels: .Net MAUI

#247 feat[maui]: Added Settings Functionality To Enhance Login Flow Views
  SysCredit/Properties/SysCreditResources.Designer.cs
  SysCredit/Properties/SysCreditResources.es.resx
  SysCredit/Properties/SysCreditResources.resx
  SysCredit/Resources/Styles/LoginStyles.xaml
  SysCredit/Views/Users/LoginPage.xaml
  SysCredit/Views/Users/RecoverAccountPage.xaml
Labels: frontend

#248 feat[maui]: Modify Side Menu
  SysCredit/AppShell.xaml
Labels: frontend, .Net MAUI

#250 feat[maui]: Added Customer Guarantor View Feature
  SysCredit/Mockup/GuarantorRepository.cs
  SysCredit/Services/SysCreditApi/SysCreditApiService.cs
  SysCredit/ViewModels/Guarantors/GuarantorRegistrationViewModel.cs
  SysCredit/ViewModels/Guarantors/GuarantorSearchViewModel.cs
Labels: frontend

#249 feat[maui]: Add Functionality To Create Customer
  SysCredit/Mockup/CustomerRepository.cs
  SysCredit/Models/Customers/Creates/CreateCustomer.cs
  SysCredit/Models/Customers/Creates/CreateReference.cs
  SysCredit/Properties/SysCreditResources.Designer.cs
  SysCredit/Properties/SysCreditResources.es.resx
  SysCredit/Properties/SysCreditResources.resx
  SysCredit/Services/SysCreditApi/SysCreditApiService.cs
  SysCredit/SysCredit.csproj
  SysCredit/Validations/EmailAddressIfNotEmptyAttribute.cs
  SysCredit/Validations/FieldMustBeAStringAttribute.cs
  SysCredit/Views/Customers/CustomerRegistrationPage.xaml
Labels: frontend, .Net MAUI, Business Logic
